version: '3.7'

services:
  weatherbot:
    image: weatherbot
    build:
      context:
        .
    command:
      - python
      - -m
      - weatherbot
      - bot
    environment:
      POSTGRES_HOST: postgres
  notifier:
    image: weatherbot
    command:
      - python
      - -m
      - weatherbot
      - notify
    environment:
      POSTGRES_HOST: postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: weatherdb
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: weatherdb
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db-data: null
